// Generated by scripts/build_karaoke_lyrics.py. Do not edit directly.
const Karaoke = Object.create(null);

// source: src/track-adapter.js
Karaoke.readTrack = function () {
  const transport = document.querySelector("#transportContainer");
  const vue = transport && transport.__vue__;
  const raw = vue && vue.track && typeof vue.track === "object" ? vue.track : {};
  const progress = vue && vue.playbackProgress && typeof vue.playbackProgress === "object" ? vue.playbackProgress : {};
  const artistsRaw = raw.artists || raw.artist || [];
  const artists = Array.isArray(artistsRaw)
    ? artistsRaw.map(function (item) { return String((item && (item.name || item.artistName)) || item || ""); }).filter(Boolean)
    : [String((artistsRaw && (artistsRaw.name || artistsRaw.artistName)) || artistsRaw || "")].filter(Boolean);
  const title = String(raw.title || raw.name || (transport && transport.querySelector(".trackTitle") && transport.querySelector(".trackTitle").textContent) || "").trim();
  const amazonId = String(raw.asin || raw.id || "").trim();
  let durationMs = Number(raw.duration || raw.durationMs || progress.duration || 0);
  if (durationMs > 0 && durationMs < 10000) durationMs *= 1000;
  const hostname = String(location.hostname || "music.amazon.com").toLowerCase();
  const fingerprint = [title, artists.join(","), raw.album && (raw.album.name || raw.album.title || raw.album), durationMs].join("|").toLowerCase();
  let hash = 2166136261;
  for (let index = 0; index < fingerprint.length; index += 1) {
    hash ^= fingerprint.charCodeAt(index);
    hash = Math.imul(hash, 16777619);
  }
  const lyricsData = raw.lyricsData && typeof raw.lyricsData === "object" ? raw.lyricsData : null;
  return {
    key: amazonId ? "amazon:" + hostname + ":" + amazonId : "metadata:" + String(hash >>> 0),
    amazonId: amazonId,
    marketplace: hostname,
    title: title,
    artists: artists,
    album: String((raw.album && (raw.album.name || raw.album.title)) || raw.albumName || raw.album || ""),
    durationMs: Math.max(0, Math.round(durationMs || 0)),
    artworkUrl: String(raw.imageUrl || raw.artworkUrl || raw.image || ""),
    explicit: Boolean(raw.explicit || raw.isExplicit),
    isrc: String(raw.isrc || ""),
    hasLyrics: Boolean(raw.hasLyrics || lyricsData),
    amazonLyrics: lyricsData,
    currentTimeMs: Math.max(0, Number(progress.currentTime || 0)),
    playing: Karaoke.isPlaying()
  };
};

Karaoke.isPlaying = function () {
  const transport = document.querySelector("#transportContainer");
  const vue = transport && transport.__vue__;
  return String((vue && vue.playerModel && vue.playerModel.state) || "").toLowerCase() === "playing";
};

Karaoke.readPlaybackTime = function () {
  const transport = document.querySelector("#transportContainer");
  const vue = transport && transport.__vue__;
  const value = Number(vue && vue.playbackProgress && vue.playbackProgress.currentTime);
  return Number.isFinite(value) ? Math.max(0, value) : 0;
};

Karaoke.seek = function (timeMs) {
  const transport = document.querySelector("#transportContainer");
  const vue = transport && transport.__vue__;
  const progress = vue && vue.playbackProgress;
  let durationMs = Number(progress && progress.duration) || Number(vue && vue.track && (vue.track.durationMs || vue.track.duration)) || 0;
  if (durationMs > 0 && durationMs < 10000) durationMs *= 1000;
  const slider = transport && transport.querySelector(".slider.progressBar, [class*='progressBar']");
  if (!slider || !durationMs) return false;
  const fraction = Math.max(0, Math.min(1, (Number(timeMs) || 0) / durationMs));
  const rect = slider.getBoundingClientRect();
  if (!rect.width) return false;
  const x = rect.left + rect.width * fraction;
  const y = rect.top + rect.height / 2;
  ["mousedown", "mouseup", "click"].forEach(function (type) {
    slider.dispatchEvent(new MouseEvent(type, { bubbles: true, cancelable: true, view: window, clientX: x, clientY: y, button: 0, buttons: type === "mousedown" ? 1 : 0 }));
  });
  return true;
};

// source: src/slobjpack.js
Karaoke.unpackSLObjPack = function (packed) {
  if (!Array.isArray(packed) || packed.length !== 2 || !Array.isArray(packed[0]) || !Array.isArray(packed[1])) return packed;
  const values = packed[0];
  const stream = packed[1];
  if (values.length > 50000 || stream.length > 250000 || JSON.stringify(packed).length > 4000000) throw new Error("Packed lyrics exceed limits");
  let cursor = 0;
  let nodes = 0;
  function read() {
    if (cursor >= stream.length || cursor > 250000) throw new Error("Packed lyrics ended early");
    return stream[cursor++];
  }
  function count(value, limit, label) {
    if (!Number.isInteger(value) || value < 0 || value > limit) throw new Error("Packed lyrics " + label + " is invalid");
    return value;
  }
  function pointer(index) {
    if (!Number.isInteger(index) || index < 0 || index >= values.length) throw new Error("Packed lyrics pointer is invalid");
    const value = values[index];
    if (typeof value === "string" && value.length > 100000) throw new Error("Packed lyrics string is too large");
    return value;
  }
  function key() {
    const value = pointer(read());
    if (typeof value !== "string" || value.length > 256 || value === "__proto__" || value === "prototype" || value === "constructor") throw new Error("Packed lyrics key is unsafe");
    return value;
  }
  function decode(depth) {
    nodes += 1;
    if (depth > 64 || nodes > 100000) throw new Error("Packed lyrics are too complex");
    const op = read();
    if (!Number.isInteger(op)) throw new Error("Packed lyrics opcode is invalid");
    if (op >= 0) return pointer(op);
    if (op === -4) return [];
    if (op === -5) return [decode(depth + 1)];
    if (op === -6) return Object.create(null);
    if (op === -2) {
      const length = count(read(), 50000, "array length");
      const array = [];
      for (let index = 0; index < length; index += 1) array.push(decode(depth + 1));
      return array;
    }
    if (op === -1 || op === -3) {
      const itemCount = op === -3 ? count(read(), 10000, "item count") : 1;
      const keyCount = count(read(), 512, "key count");
      const keys = [];
      for (let index = 0; index < keyCount; index += 1) keys.push(key());
      const output = [];
      for (let item = 0; item < itemCount; item += 1) {
        const object = Object.create(null);
        for (let index = 0; index < keys.length; index += 1) object[keys[index]] = decode(depth + 1);
        output.push(object);
      }
      return op === -1 ? output[0] : output;
    }
    throw new Error("Packed lyrics opcode is unknown");
  }
  const result = decode(0);
  if (cursor !== stream.length) throw new Error("Packed lyrics contain trailing operations");
  return result;
};

// source: src/normalization.js
Karaoke.number = function (value) {
  const parsed = Number(value);
  return Number.isFinite(parsed) ? Math.max(0, parsed) : 0;
};

Karaoke.timeMs = function (value) {
  return Karaoke.number(value);
};

Karaoke.normalizeWords = function (syllables) {
  if (!Array.isArray(syllables)) return [];
  const words = [];
  let current = null;
  syllables.forEach(function (raw) {
    if (!raw || typeof raw !== "object") return;
    const text = String(raw.Text || raw.text || "");
    if (!text) return;
    const token = {
      text: text,
      startMs: Karaoke.timeMs(raw.StartTime != null ? raw.StartTime : raw.startTime),
      endMs: Karaoke.timeMs(raw.EndTime != null ? raw.EndTime : raw.endTime)
    };
    const part = Boolean(raw.IsPartOfWord || raw.isPartOfWord);
    if (part && current) {
      current.text += text;
      current.endMs = Math.max(current.endMs, token.endMs);
      current.syllables.push(token);
    } else {
      current = { text: text, startMs: token.startMs, endMs: token.endMs, syllables: [token] };
      words.push(current);
    }
  });
  return words;
};

Karaoke.normalizeSpicy = function (packed, trackKey) {
  const raw = Karaoke.unpackSLObjPack(packed);
  if (!raw || typeof raw !== "object") return null;
  const type = String(raw.Type || raw.type || "").toLowerCase();
  const content = Array.isArray(raw.Content) ? raw.Content : (Array.isArray(raw.content) ? raw.content : []);
  const lines = [];
  content.forEach(function (entry, lineIndex) {
    if (!entry) return;
    const item = typeof entry === "object" ? entry : { Text: String(entry) };
    const lead = item.Lead || item.lead || item;
    const syllables = lead && (lead.Syllables || lead.syllables);
    const words = Karaoke.normalizeWords(syllables);
    let text = String((lead && (lead.Text || lead.text)) || item.Text || item.text || "").trim();
    if (!text && words.length) text = words.map(function (word) { return word.text; }).join(" ");
    if (!text) return;
    let startMs = Karaoke.timeMs(lead.StartTime != null ? lead.StartTime : lead.startTime);
    let endMs = Karaoke.timeMs(lead.EndTime != null ? lead.EndTime : lead.endTime);
    if (words.length) {
      startMs = startMs || words[0].startMs;
      endMs = endMs || words[words.length - 1].endMs;
    }
    lines.push({
      id: "spicy-" + lineIndex,
      text: text,
      startMs: startMs,
      endMs: Math.max(startMs, endMs),
      words: words,
      translation: String(item.Translation || item.translation || ""),
      background: Boolean(item.Background || item.background)
    });
  });
  if (!lines.length) return null;
  let modelType = "line";
  if (type.indexOf("static") >= 0 || !lines.some(function (line) { return line.startMs || line.endMs; })) modelType = "static";
  else if (lines.some(function (line) { return line.words.length && line.words.some(function (word) { return word.endMs > word.startMs; }); })) modelType = "syllable";
  return Object.freeze({
    schemaVersion: 1,
    type: modelType,
    source: "spicy-lyrics",
    trackKey: trackKey,
    language: String(raw.Language || raw.language || ""),
    credits: raw.Credits || raw.credits || null,
    lines: lines
  });
};

Karaoke.normalizeAmazon = function (lyricsData, trackKey) {
  if (!lyricsData || typeof lyricsData !== "object") return null;
  const nested = lyricsData.lyrics && typeof lyricsData.lyrics === "object" ? lyricsData.lyrics : lyricsData;
  let rawLines = nested.lines || nested.Lines || nested.content || [];
  if (!Array.isArray(rawLines) && typeof rawLines === "string") rawLines = rawLines.split(/\r?\n/);
  if (!Array.isArray(rawLines)) return null;
  const lines = [];
  rawLines.forEach(function (raw, index) {
    const item = raw && typeof raw === "object" ? raw : { text: raw };
    const text = String(item.text || item.lyric || item.line || item.words || "").trim();
    if (!text) return;
    const startMs = Karaoke.timeMs(item.startTime != null ? item.startTime : (item.startTimeMs != null ? item.startTimeMs : item.start));
    const endMs = Karaoke.timeMs(item.endTime != null ? item.endTime : (item.endTimeMs != null ? item.endTimeMs : item.end));
    lines.push({ id: "amazon-" + index, text: text, startMs: startMs, endMs: Math.max(startMs, endMs), words: [], translation: "", background: false });
  });
  if (!lines.length) return null;
  for (let index = 0; index < lines.length - 1; index += 1) {
    if (!lines[index].endMs && lines[index + 1].startMs) lines[index].endMs = lines[index + 1].startMs;
  }
  const timed = lines.some(function (line) { return line.startMs > 0 || line.endMs > 0; });
  return Object.freeze({ schemaVersion: 1, type: timed ? "line" : "static", source: "amazon", trackKey: trackKey, language: String(nested.language || ""), credits: nested.credits || null, lines: lines });
};

Karaoke.findActiveLine = function (lines, timeMs) {
  let low = 0;
  let high = lines.length - 1;
  let answer = -1;
  while (low <= high) {
    const middle = (low + high) >> 1;
    if (lines[middle].startMs <= timeMs) { answer = middle; low = middle + 1; }
    else high = middle - 1;
  }
  return answer;
};

Karaoke.progress = function (timeMs, startMs, endMs) {
  if (!(endMs > startMs)) return timeMs >= startMs ? 1 : 0;
  return Math.max(0, Math.min(1, (timeMs - startMs) / (endMs - startMs)));
};

// source: src/renderer.js
Karaoke.Renderer = function (onSeek) {
  this.node = document.createElement("div");
  this.node.className = "amazify-karaoke-host";
  this.node.dataset.amazifyPluginId = "amazify.karaoke-lyrics";
  this.node.dataset.presentation = "normal";
  this.scroller = document.createElement("div");
  this.scroller.className = "amazify-karaoke-scroller";
  this.node.appendChild(this.scroller);
  this.model = null;
  this.lineNodes = [];
  this.wordNodes = [];
  this.activeLine = -1;
  this.activeWord = -1;
  this.manualUntil = 0;
  this.programmaticUntil = 0;
  this.scrollTimer = 0;
  this.onSeek = onSeek;
  const renderer = this;
  ["wheel", "touchstart", "pointerdown", "keydown"].forEach(function (name) {
    renderer.scroller.addEventListener(name, function () { renderer.markManual(); }, { passive: true });
  });
  this.scroller.addEventListener("scroll", function () {
    if (performance.now() >= renderer.programmaticUntil) renderer.markManual();
  }, { passive: true });
  this.resizeObserver = typeof ResizeObserver === "function"
    ? new ResizeObserver(function () { renderer.centerActive(false); })
    : null;
  if (this.resizeObserver) this.resizeObserver.observe(this.node);
};

Karaoke.Renderer.prototype.markManual = function () {
  this.manualUntil = performance.now() + 4000;
  this.node.classList.add("is-manual-scroll");
  clearTimeout(this.scrollTimer);
  const renderer = this;
  this.scrollTimer = setTimeout(function () { renderer.node.classList.remove("is-manual-scroll"); }, 1100);
};

Karaoke.Renderer.prototype.setModel = function (model) {
  if (this.model === model) return;
  this.model = model;
  this.activeLine = -1;
  this.activeWord = -1;
  while (this.scroller.firstChild) this.scroller.removeChild(this.scroller.firstChild);
  this.lineNodes = [];
  this.wordNodes = [];
  const renderer = this;
  if (!model || !model.lines.length) {
    const empty = document.createElement("div");
    empty.className = "amazify-karaoke-empty";
    empty.textContent = "Lyrics aren't available for this song.";
    this.scroller.appendChild(empty);
    this.node.dataset.ready = "true";
    return;
  }
  model.lines.forEach(function (line, lineIndex) {
    const element = document.createElement("button");
    element.type = "button";
    element.className = "amazify-karaoke-line";
    element.dataset.lineIndex = String(lineIndex);
    element.setAttribute("aria-label", line.text);
    const words = [];
    if (line.words.length && model.type === "syllable") {
      line.words.forEach(function (word, wordIndex) {
        if (wordIndex) element.appendChild(document.createTextNode(" "));
        const token = document.createElement("span");
        token.className = "amazify-karaoke-word";
        token.textContent = word.text;
        token.style.setProperty("--lyric-progress", "0");
        element.appendChild(token);
        words.push(token);
      });
    } else {
      element.textContent = line.text;
    }
    if (line.translation) {
      const translation = document.createElement("small");
      translation.textContent = line.translation;
      element.appendChild(translation);
    }
    element.addEventListener("click", function () {
      renderer.manualUntil = 0;
      renderer.onSeek(line.startMs);
    });
    renderer.scroller.appendChild(element);
    renderer.lineNodes.push(element);
    renderer.wordNodes.push(words);
  });
  this.node.dataset.ready = "true";
};

Karaoke.Renderer.prototype.update = function (timeMs, forceScroll) {
  if (!this.model || this.model.type === "static") return;
  const lineIndex = Karaoke.findActiveLine(this.model.lines, timeMs);
  if (lineIndex !== this.activeLine) {
    if (this.lineNodes[this.activeLine]) this.lineNodes[this.activeLine].classList.remove("is-active");
    this.activeLine = lineIndex;
    this.activeWord = -1;
    if (this.lineNodes[lineIndex]) this.lineNodes[lineIndex].classList.add("is-active");
    this.centerActive(Boolean(forceScroll));
  }
  const line = this.model.lines[lineIndex];
  const nodes = this.wordNodes[lineIndex] || [];
  if (!line || !nodes.length) return;
  let activeWord = -1;
  for (let index = 0; index < line.words.length; index += 1) {
    const word = line.words[index];
    const value = Karaoke.progress(timeMs, word.startMs, word.endMs);
    nodes[index].style.setProperty("--lyric-progress", String(value));
    nodes[index].classList.toggle("is-sung", value >= 1);
    if (value > 0 && value < 1) activeWord = index;
  }
  if (activeWord !== this.activeWord) {
    if (nodes[this.activeWord]) nodes[this.activeWord].classList.remove("is-active");
    this.activeWord = activeWord;
    if (nodes[activeWord]) nodes[activeWord].classList.add("is-active");
  }
};

Karaoke.Renderer.prototype.centerActive = function (force) {
  const target = this.lineNodes[this.activeLine];
  if (!target || (!force && performance.now() < this.manualUntil)) return;
  const reducedMotion = window.matchMedia && window.matchMedia("(prefers-reduced-motion: reduce)").matches;
  this.programmaticUntil = performance.now() + (reducedMotion ? 100 : 1200);
  target.scrollIntoView({ behavior: reducedMotion ? "auto" : "smooth", block: "center" });
};

Karaoke.Renderer.prototype.claim = function (container, presentation) {
  if (!container) return;
  this.node.dataset.presentation = presentation || "normal";
  if (this.node.parentNode !== container) container.appendChild(this.node);
  this.centerActive(true);
};

Karaoke.Renderer.prototype.destroy = function () {
  clearTimeout(this.scrollTimer);
  if (this.resizeObserver) this.resizeObserver.disconnect();
  this.node.remove();
};

// source: src/session.js
Karaoke.Session = function (provider) {
  this.provider = provider;
  this.track = null;
  this.model = null;
  this.status = "idle";
  this.providerStatus = null;
  this.generation = 0;
  this.requestKey = "";
  this.listeners = new Set();
  this.claims = new Set();
  this.defaultHost = null;
  this.activeClaim = null;
  this.raf = 0;
  this.renderer = new Karaoke.Renderer(Karaoke.seek);
  this.destroyed = false;
};

Karaoke.Session.prototype.snapshot = function () {
  return Object.freeze({
    track: this.track ? Object.freeze(Object.assign({}, this.track, { amazonLyrics: undefined })) : null,
    status: this.status,
    source: this.model ? this.model.source : "",
    type: this.model ? this.model.type : "",
    hasLyrics: Boolean(this.model && this.model.lines.length),
    providerStatus: this.providerStatus ? Object.freeze(Object.assign({}, this.providerStatus)) : null
  });
};

Karaoke.Session.prototype.publish = function () {
  const snapshot = this.snapshot();
  this.listeners.forEach(function (listener) {
    try { listener(snapshot); } catch (error) { console.warn("[Karaoke Lyrics] listener failed", error); }
  });
};

Karaoke.Session.prototype.subscribe = function (listener) {
  this.listeners.add(listener);
  listener(this.snapshot());
  const session = this;
  return function () { session.listeners.delete(listener); };
};

Karaoke.Session.prototype.setTrack = function (track) {
  if (!track || !track.key || (this.track && this.track.key === track.key)) {
    if (track) this.track = track;
    return;
  }
  if (this.requestKey) this.provider.cancel(this.requestKey).catch(function () {});
  this.generation += 1;
  this.track = track;
  this.model = Karaoke.normalizeAmazon(track.amazonLyrics, track.key);
  this.status = this.model ? "ready" : "idle";
  this.requestKey = "";
  this.renderer.setModel(this.model);
  this.publish();
  this.ensureLoad();
};

Karaoke.Session.prototype.ensureLoad = function () {
  if (!this.track || this.requestKey || !this.visible()) return;
  const generation = this.generation;
  const track = this.track;
  const requestKey = track.key + ":" + generation + ":" + Math.random().toString(36).slice(2);
  this.requestKey = requestKey;
  this.status = this.model ? "ready" : "loading";
  this.publish();
  const session = this;
  this.provider.load(track, requestKey).then(function (result) {
    if (session.destroyed || generation !== session.generation || requestKey !== session.requestKey || !session.track || result.trackKey !== session.track.key) return;
    session.requestKey = "";
    if (result.status === "ready" && result.payload != null) {
      try {
        const upgraded = Karaoke.normalizeSpicy(result.payload, track.key);
        if (upgraded) session.model = upgraded;
      } catch (error) {
        console.warn("[Karaoke Lyrics] provider payload rejected", error);
      }
    }
    session.providerStatus = { status: result.status || "unavailable", detail: result.detail || "", cached: Boolean(result.cached) };
    session.status = session.model ? "ready" : "no-lyrics";
    session.renderer.setModel(session.model);
    session.publish();
    session.syncHost();
    session.startRaf();
  }).catch(function (error) {
    if (generation !== session.generation || requestKey !== session.requestKey) return;
    session.requestKey = "";
    session.providerStatus = { status: "error", detail: String(error && error.message || error) };
    session.status = session.model ? "ready" : "no-lyrics";
    session.renderer.setModel(session.model);
    session.publish();
    session.syncHost();
  });
};

Karaoke.Session.prototype.setDefaultHost = function (container) {
  this.defaultHost = container || null;
  this.syncHost();
  this.ensureLoad();
};

Karaoke.Session.prototype.claimHost = function (container, options) {
  if (!container || !container.nodeType) throw new TypeError("Lyrics host must be a DOM element");
  const claim = {
    container: container,
    presentation: String(options && options.presentation || "normal"),
    priority: Number(options && options.priority || 0),
    order: Date.now() + Math.random(),
    active: true
  };
  this.claims.add(claim);
  this.syncHost();
  this.ensureLoad();
  const session = this;
  return function () {
    if (!claim.active) return;
    claim.active = false;
    session.claims.delete(claim);
    session.syncHost();
  };
};

Karaoke.Session.prototype.syncHost = function () {
  let selected = null;
  this.claims.forEach(function (claim) {
    if (!claim.active || !claim.container.isConnected) return;
    if (!selected || claim.priority > selected.priority || (claim.priority === selected.priority && claim.order > selected.order)) selected = claim;
  });
  this.activeClaim = selected;
  const host = selected ? selected.container : this.defaultHost;
  const presentation = selected ? selected.presentation : "normal";
  if (host && host.isConnected) this.renderer.claim(host, presentation);
  this.startRaf();
};

Karaoke.Session.prototype.visible = function () {
  const node = this.renderer.node;
  if (!node.isConnected || document.visibilityState === "hidden") return false;
  const style = getComputedStyle(node);
  return style.display !== "none" && style.visibility !== "hidden" && node.getClientRects().length > 0;
};

Karaoke.Session.prototype.startRaf = function () {
  if (this.raf || !this.model || this.model.type === "static" || !this.visible()) return;
  const session = this;
  function frame() {
    session.raf = 0;
    if (session.destroyed || !session.model || session.model.type === "static" || !session.visible()) return;
    session.renderer.update(Karaoke.readPlaybackTime(), false);
    if (!Karaoke.isPlaying()) return;
    session.raf = requestAnimationFrame(frame);
  }
  this.raf = requestAnimationFrame(frame);
};

Karaoke.Session.prototype.refreshProviderStatus = function () {
  const session = this;
  return this.provider.status().then(function (status) {
    session.providerStatus = status.spotify || status;
    session.publish();
    return status;
  });
};

Karaoke.Session.prototype.destroy = function () {
  this.destroyed = true;
  if (this.requestKey) this.provider.cancel(this.requestKey).catch(function () {});
  cancelAnimationFrame(this.raf);
  this.raf = 0;
  this.listeners.clear();
  this.claims.clear();
  this.renderer.destroy();
};

// source: src/integration.js
Karaoke.Integration = function (session) {
  this.session = session;
  this.observer = null;
  this.interval = 0;
  this.wrapper = null;
  this.nativeList = null;
  this.unsubscribe = null;
};

Karaoke.Integration.prototype.start = function () {
  const integration = this;
  this.unsubscribe = this.session.subscribe(function () { integration.sync(); });
  this.observer = new MutationObserver(function () { integration.sync(); });
  this.observer.observe(document.documentElement, { childList: true, subtree: true });
  this.interval = setInterval(function () { integration.sync(); }, 750);
  document.addEventListener("visibilitychange", this._visibility = function () {
    integration.sync();
    integration.session.startRaf();
  });
  this.sync();
};

Karaoke.Integration.prototype.sync = function () {
  const track = Karaoke.readTrack();
  if (track && track.key) this.session.setTrack(track);
  const wrapper = document.querySelector(".nowPlayingView.x4 .lyricsContainer .lyricsWrapper");
  const nativeList = wrapper && wrapper.querySelector("ul.lyricsScroller");
  if (this.wrapper && this.wrapper !== wrapper) {
    this.wrapper.classList.remove("amazify-karaoke-enhanced");
    this.wrapper.removeAttribute("data-amazify-karaoke-status");
  }
  this.wrapper = wrapper;
  this.nativeList = nativeList;
  this.session.setDefaultHost(wrapper);
  if (!wrapper) return;
  wrapper.setAttribute("data-amazify-karaoke-status", this.session.status);
  wrapper.classList.toggle("amazify-karaoke-enhanced", this.session.status === "ready" || this.session.status === "no-lyrics");
  this.session.ensureLoad();
  this.session.startRaf();
};

Karaoke.Integration.prototype.destroy = function () {
  if (this.observer) this.observer.disconnect();
  clearInterval(this.interval);
  document.removeEventListener("visibilitychange", this._visibility);
  if (this.unsubscribe) this.unsubscribe();
  if (this.wrapper) {
    this.wrapper.classList.remove("amazify-karaoke-enhanced");
    this.wrapper.removeAttribute("data-amazify-karaoke-status");
  }
};

// source: src/settings.js
Karaoke.addSettings = function (Amazify, session) {
  return Amazify.ui.addSettingsSection({
    id: "provider",
    title: "Karaoke Lyrics",
    render: function (host) {
      host.className = "amazify-karaoke-settings";
      const status = document.createElement("div");
      status.className = "amazify-setting-row amazify-karaoke-provider-status";
      const actions = document.createElement("div");
      actions.className = "amazify-karaoke-settings-actions";
      host.appendChild(status);
      host.appendChild(actions);
      let alive = true;
      function button(label, handler) {
        const element = document.createElement("button");
        element.type = "button";
        element.textContent = label;
        element.addEventListener("click", handler);
        actions.appendChild(element);
      }
      function render(providerStatus) {
        if (!alive) return;
        const spotify = providerStatus && providerStatus.spotify ? providerStatus.spotify : providerStatus;
        const state = spotify && spotify.state || "checking";
        status.textContent = "Spotify beta: " + state + (spotify && spotify.detail ? " - " + spotify.detail : "");
        while (actions.firstChild) actions.removeChild(actions.firstChild);
        if (state === "connected") {
          button("Reconnect", function () { Amazify.lyricsProvider.beginAuth().then(refresh); });
          button("Disconnect", function () { Amazify.lyricsProvider.disconnect().then(refresh); });
        } else {
          button("Connect Spotify", function () { Amazify.lyricsProvider.beginAuth().then(refresh); });
        }
        button("Clear lyrics cache", function () { Amazify.lyricsProvider.clearCache().then(refresh); });
      }
      function refresh() {
        return Amazify.lyricsProvider.status().then(function (value) { render(value); return value; }).catch(function (error) { render({ state: "error", detail: String(error.message || error) }); });
      }
      refresh();
      const timer = setInterval(refresh, 3000);
      return function () { alive = false; clearInterval(timer); };
    }
  });
};

// source: src/bootstrap.js
Karaoke.versionAtLeast = function (actual, required) {
  const left = String(actual || "0").split(".").map(Number);
  const right = String(required || "0").split(".").map(Number);
  for (let index = 0; index < 3; index += 1) {
    if ((left[index] || 0) > (right[index] || 0)) return true;
    if ((left[index] || 0) < (right[index] || 0)) return false;
  }
  return true;
};

Karaoke.cleanLegacyStorage = function () {
  [window.localStorage, window.sessionStorage].forEach(function (storage) {
    try {
      const removals = [];
      for (let index = 0; index < storage.length; index += 1) {
        const key = storage.key(index);
        if (key === "amazify.true-big-mode.spotifyAccessToken" || key === "amazify.true-big-mode.spotifyTrackId" || String(key || "").indexOf("amazify.true-big-mode.spotifyTrackId.") === 0) removals.push(key);
      }
      removals.forEach(function (key) { storage.removeItem(key); });
    } catch (_error) {}
  });
};

Karaoke.bootstrap = function (Amazify) {
  if (!Karaoke.versionAtLeast(Amazify.version, "1.1.0")) throw new Error("Karaoke Lyrics requires Amazify 1.1.0 or newer");
  if (!Amazify.lyricsProvider) throw new Error("Karaoke Lyrics provider permission is unavailable");
  Karaoke.cleanLegacyStorage();
  document.querySelectorAll('.amazify-karaoke-host[data-amazify-plugin-id="amazify.karaoke-lyrics"], .amazify-karaoke-host:not([data-amazify-plugin-id])').forEach(function (node) { node.remove(); });
  const session = new Karaoke.Session(Amazify.lyricsProvider);
  const integration = new Karaoke.Integration(session);
  integration.start();
  const releaseCapability = Amazify.capabilities.provide("amazify.karaoke-lyrics.presentation", {
    version: "1.0.0",
    api: {
      getSnapshot: function () { return session.snapshot(); },
      subscribe: function (listener) { return session.subscribe(listener); },
      claimHost: function (container, options) { return session.claimHost(container, options); }
    }
  });
  const removeSettings = Karaoke.addSettings(Amazify, session);
  session.refreshProviderStatus().catch(function () {});
  return function () {
    try {
      removeSettings();
    } catch (error) {
      console.warn("[Karaoke Lyrics] settings cleanup failed", error);
    }
    try {
      releaseCapability();
    } catch (error) {
      console.warn("[Karaoke Lyrics] capability cleanup failed", error);
    }
    try {
      integration.destroy();
    } catch (error) {
      console.warn("[Karaoke Lyrics] integration cleanup failed", error);
    }
    session.destroy();
  };
};

return Karaoke.bootstrap(Amazify, manifest, source);
