from __future__ import annotations

import argparse
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PLUGIN = ROOT / "sample_plugins" / "Scrapped" / "amazify.karaoke-lyrics"
SOURCES = (
    "track-adapter.js",
    "slobjpack.js",
    "normalization.js",
    "renderer.js",
    "session.js",
    "integration.js",
    "settings.js",
    "bootstrap.js",
)


def build() -> str:
    sections = [
        "// Generated by scripts/build_karaoke_lyrics.py. Do not edit directly.\n",
        "const Karaoke = Object.create(null);\n",
    ]
    for name in SOURCES:
        source = (PLUGIN / "src" / name).read_text(encoding="utf-8").rstrip()
        sections.append(f"\n// source: src/{name}\n{source}\n")
    sections.append("\nreturn Karaoke.bootstrap(Amazify, manifest, source);\n")
    return "".join(sections)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    output = PLUGIN / "plugin.js"
    generated = build()
    if args.check:
        if not output.exists() or output.read_text(encoding="utf-8") != generated:
            raise SystemExit("Karaoke Lyrics bundle is stale; run scripts/build_karaoke_lyrics.py")
        return 0
    output.write_text(generated, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
