// Generated by scripts/build_karaoke_lyrics.py. Do not edit directly.
const Karaoke = Object.create(null);

// source: src/track-adapter.js
Karaoke.readTrack = function () {
  const transport = document.querySelector("#transportContainer");
  const vue = transport && transport.__vue__;
  const raw = vue && vue.track && typeof vue.track === "object" ? vue.track : {};
  const progress = vue && vue.playbackProgress && typeof vue.playbackProgress === "object" ? vue.playbackProgress : {};
  const artistsRaw = raw.artists || raw.artist || [];
  const artists = Array.isArray(artistsRaw)
    ? artistsRaw.map(function (item) { return String((item && (item.name || item.artistName)) || item || ""); }).filter(Boolean)
    : [String((artistsRaw && (artistsRaw.name || artistsRaw.artistName)) || artistsRaw || "")].filter(Boolean);
  const title = String(raw.title || raw.name || (transport && transport.querySelector(".trackTitle") && transport.querySelector(".trackTitle").textContent) || "").trim();
  const amazonId = String(raw.asin || raw.id || "").trim();
  const durationMs = Karaoke.durationMs(raw, progress);
  const hostname = String(location.hostname || "music.amazon.com").toLowerCase();
  const fingerprint = [title, artists.join(","), raw.album && (raw.album.name || raw.album.title || raw.album), durationMs].join("|").toLowerCase();
  let hash = 2166136261;
  for (let index = 0; index < fingerprint.length; index += 1) {
    hash ^= fingerprint.charCodeAt(index);
    hash = Math.imul(hash, 16777619);
  }
  const lyricsData = raw.lyricsData && typeof raw.lyricsData === "object" ? raw.lyricsData : null;
  return {
    key: amazonId ? "amazon:" + hostname + ":" + amazonId : "metadata:" + String(hash >>> 0),
    amazonId: amazonId,
    marketplace: hostname,
    title: title,
    artists: artists,
    album: String((raw.album && (raw.album.name || raw.album.title)) || raw.albumName || raw.album || ""),
    durationMs: Math.max(0, Math.round(durationMs || 0)),
    artworkUrl: String(raw.imageUrl || raw.artworkUrl || raw.image || ""),
    explicit: Boolean(raw.explicit || raw.isExplicit),
    isrc: String(raw.isrc || ""),
    hasLyrics: raw.hasLyrics === true || Boolean(lyricsData && lyricsData.lyrics && Array.isArray(lyricsData.lyrics.lines) && lyricsData.lyrics.lines.length),
    amazonLyrics: lyricsData,
    currentTimeMs: Math.max(0, Number(progress.currentTime || 0)),
    playing: Karaoke.isPlaying()
  };
};

Karaoke.isPlaying = function () {
  const transport = document.querySelector("#transportContainer");
  const vue = transport && transport.__vue__;
  return String((vue && vue.playerModel && vue.playerModel.state) || "").toLowerCase() === "playing";
};

Karaoke.readPlaybackTime = function () {
  const transport = document.querySelector("#transportContainer");
  const vue = transport && transport.__vue__;
  const value = Number(vue && vue.playbackProgress && vue.playbackProgress.currentTime);
  return Number.isFinite(value) ? Math.max(0, value) : 0;
};

Karaoke.seek = function (timeMs) {
  const transport = document.querySelector("#transportContainer");
  const vue = transport && transport.__vue__;
  const progress = vue && vue.playbackProgress;
  const durationMs = Karaoke.durationMs(vue && vue.track || {}, progress || {});
  const slider = transport && transport.querySelector(".slider.progressBar, [class*='progressBar']");
  if (!slider || !durationMs) return false;
  const fraction = Math.max(0, Math.min(1, (Number(timeMs) || 0) / durationMs));
  const rect = slider.getBoundingClientRect();
  if (!rect.width) return false;
  const x = rect.left + rect.width * fraction;
  const y = rect.top + rect.height / 2;
  ["mousedown", "mouseup", "click"].forEach(function (type) {
    slider.dispatchEvent(new MouseEvent(type, { bubbles: true, cancelable: true, view: window, clientX: x, clientY: y, button: 0, buttons: type === "mousedown" ? 1 : 0 }));
  });
  return true;
};

Karaoke.durationMs = function (track, progress) {
  const value = typeof track.durationMs === "number" ? track.durationMs : typeof track.duration === "number" ? track.duration * 1000 : Number(progress.duration || 0);
  return Number.isFinite(value) && value > 0 ? value : 0;
};

// source: src/normalization.js
// The native broker parses provider formats. Validate its rich-only v1 boundary again.
Karaoke.normalizeRich = function (raw, trackKey) {
  if (!raw || raw.schemaVersion !== 1 || raw.type !== "syllable" || raw.trackKey !== trackKey || !Array.isArray(raw.lines) || !raw.lines.length || raw.lines.length > 2000) return null;
  let count = 0;
  let characters = 0;
  function timed(value) {
    if (!value || typeof value.text !== "string" || !Number.isFinite(value.startMs) || !Number.isFinite(value.endMs) || value.startMs < 0 || value.endMs <= value.startMs || value.endMs > 86400000) throw new Error("Invalid rich timing");
    characters += value.text.length;
    if (++count > 30000 || characters > 500000) throw new Error("Rich lyrics exceed limits");
    return { text: value.text, startMs: value.startMs, endMs: value.endMs };
  }
  try {
    const lines = raw.lines.map(function (line) {
      const result = timed(line);
      if (!Array.isArray(line.words) || !line.words.length) throw new Error("Line-only lyrics are not an enhancement");
      let previousEnd = line.startMs;
      result.words = Object.freeze(line.words.map(function (word) {
        const normalized = timed(word);
        const syllables = Array.isArray(word.syllables) && word.syllables.length ? word.syllables : [word];
        normalized.syllables = Object.freeze(syllables.map(function (token) {
          const value = timed(token);
          if (value.startMs < previousEnd || value.endMs > line.endMs) throw new Error("Token outside line or unordered");
          previousEnd = value.endMs;
          return Object.freeze(value);
        }));
        if (normalized.text !== normalized.syllables.map(function (token) { return token.text; }).join("") || normalized.startMs !== normalized.syllables[0].startMs || normalized.endMs !== normalized.syllables[normalized.syllables.length - 1].endMs) throw new Error("Inconsistent word");
        return Object.freeze(normalized);
      }));
      if (result.text !== result.words.map(function (word) { return word.text; }).join("")) throw new Error("Inconsistent line");
      result.background = Boolean(line.background);
      result.agent = String(line.agent || "").slice(0, 100);
      return Object.freeze(result);
    });
    for (let index = 1; index < lines.length; index += 1) {
      if (lines[index].startMs < lines[index - 1].startMs) return null;
    }
    return Object.freeze({ schemaVersion: 1, type: "syllable", source: String(raw.source || ""), trackKey: trackKey, language: String(raw.language || ""), lines: Object.freeze(lines) });
  } catch (_error) { return null; }
};

Karaoke.findActiveLine = function (lines, timeMs) {
  let low = 0, high = lines.length - 1, answer = -1;
  while (low <= high) {
    const middle = (low + high) >> 1;
    if (lines[middle].startMs <= timeMs) { answer = middle; low = middle + 1; }
    else high = middle - 1;
  }
  return answer;
};

Karaoke.progress = function (timeMs, startMs, endMs) {
  return endMs > startMs ? Math.max(0, Math.min(1, (timeMs - startMs) / (endMs - startMs))) : 0;
};

// source: src/renderer.js
// Reuse native element classes and Vue's scoped-style markers, never its event handlers.
Karaoke.presentationElement = function (template, tag, className) {
  const element = document.createElement(tag);
  element.className = className;
  if (template) Array.from(template.attributes).forEach(function (attribute) {
    if (/^data-v-[a-z0-9]+$/.test(attribute.name)) element.setAttribute(attribute.name, "");
  });
  return element;
};

// A track without Amazon lyrics may never mount the native lyric component.
// Discover its scoped CSS markers, not its font values, so themes still own styling.
Karaoke.lyricScopeTemplate = function (fallback) {
  const template = Karaoke.presentationElement(fallback, "span", "lyricsText");
  let remaining = 50000;
  function inspect(rules, depth) {
    if (!rules || depth > 4) return;
    for (let index = 0; index < rules.length && remaining-- > 0; index += 1) {
      const rule = rules[index];
      const selector = String(rule.selectorText || "");
      if (/\.(lyricsText|lyricsLine|lyricsWrapper)\b/.test(selector)) {
        (selector.match(/data-v-[a-z0-9]+/g) || []).forEach(function (name) { template.setAttribute(name, ""); });
      }
      if (rule.cssRules) inspect(rule.cssRules, depth + 1);
    }
  }
  Array.from(document.styleSheets).forEach(function (sheet) {
    try { inspect(sheet.cssRules, 0); } catch (_error) { /* Cross-origin sheets stay unread. */ }
  });
  return template;
};

Karaoke.Renderer = function (onSeek) {
  this.node = document.createElement("div");
  this.node.className = "amazify-karaoke-host";
  this.node.dataset.amazifyPluginId = "amazify.karaoke-lyrics";
  this.scroller = document.createElement("ul");
  this.scroller.className = "lyricsScroller amazify-karaoke-scroller";
  this.node.appendChild(this.scroller);
  this.container = null;
  this.nativeList = null;
  this.nativeSurfaces = [];
  this.model = null;
  this.lines = [];
  this.activeLines = new Set();
  this.activeLine = -1;
  this.lastTime = null;
  this.manualUntil = 0;
  this.programmaticUntil = 0;
  this.scrollTimer = 0;
  this.resumeTimer = 0;
  this.originalPosition = null;
  this.originalScroll = 0;
  this.scopeTemplate = null;
  this.onSeek = onSeek;
  const renderer = this;
  this.markManual = function () {
    renderer.manualUntil = performance.now() + 4000;
    renderer.node.classList.add("is-manual-scroll");
    clearTimeout(renderer.scrollTimer);
    clearTimeout(renderer.resumeTimer);
    renderer.scrollTimer = setTimeout(function () { renderer.node.classList.remove("is-manual-scroll"); }, 1100);
    renderer.resumeTimer = setTimeout(function () { renderer.centerActive(false); }, 4050);
  };
  ["wheel", "touchstart", "pointerdown", "keydown"].forEach(function (name) {
    renderer.node.addEventListener(name, renderer.markManual, { passive: true });
  });
  this.node.addEventListener("scroll", function () {
    if (performance.now() >= renderer.programmaticUntil) renderer.markManual();
  }, { passive: true });
  this.resizeObserver = typeof ResizeObserver === "function" ? new ResizeObserver(function () { renderer.measure(); renderer.centerActive(false); }) : null;
  if (this.resizeObserver) this.resizeObserver.observe(this.node);
};

Karaoke.Renderer.prototype.setModel = function (model) {
  if (this.model === model) return;
  this.release();
  this.model = model;
  this.lastTime = null;
  this.manualUntil = 0;
  this.activeLine = -1;
  this.activeLines.clear();
  this.lines = [];
  this.scroller.textContent = "";
  if (!model) { this.release(); return; }
  const renderer = this;
  model.lines.forEach(function (line) {
    const row = Karaoke.presentationElement(null, "li", "lyricsLine amazify-karaoke-line");
    const text = Karaoke.presentationElement(null, "span", "lyricsText");
    row.appendChild(text);
    row.tabIndex = 0;
    row.setAttribute("role", "button");
    row.setAttribute("aria-label", line.text);
    text.dir = "auto";
    const tokens = [];
    line.words.forEach(function (word) {
      word.syllables.forEach(function (syllable) {
        const token = document.createElement("span");
        token.className = "amazify-karaoke-token";
        token.textContent = syllable.text;
        text.appendChild(token);
        tokens.push({ node: token, timing: syllable, progress: -1 });
      });
    });
    function seek() {
      renderer.manualUntil = 0;
      clearTimeout(renderer.resumeTimer);
      renderer.onSeek(line.startMs);
      renderer.update(line.startMs, true);
    }
    row.addEventListener("click", seek);
    row.addEventListener("keydown", function (event) {
      if (event.key === "Enter" || event.key === " ") { event.preventDefault(); seek(); }
    });
    renderer.scroller.appendChild(row);
    renderer.lines.push({ row: row, text: text, tokens: tokens });
  });
};

Karaoke.Renderer.prototype.update = function (timeMs, forceScroll) {
  if (!this.model) return;
  const seek = this.lastTime !== null && (timeMs < this.lastTime - 100 || timeMs - this.lastTime > 1500);
  this.lastTime = timeMs;
  if (seek) this.manualUntil = 0;
  const last = Karaoke.findActiveLine(this.model.lines, timeMs);
  const active = new Set();
  // Overlapping lead/background lines can both be active. DOM writes remain changed-only.
  for (let index = 0; index <= last; index += 1) {
    if (this.model.lines[index].endMs > timeMs) active.add(index);
  }
  const changed = new Set(Array.from(this.activeLines).concat(Array.from(active)));
  const renderer = this;
  changed.forEach(function (index) {
    const line = renderer.lines[index];
    line.row.classList.toggle("current", active.has(index));
    line.tokens.forEach(function (token) {
      const value = Math.round(Karaoke.progress(timeMs, token.timing.startMs, token.timing.endMs) * 1000) / 1000;
      if (value !== token.progress) {
        token.progress = value;
        token.node.style.setProperty("--lyric-progress", String(value * 100) + "%");
      }
    });
  });
  this.activeLines = active;
  if (last !== this.activeLine || forceScroll || seek) {
    this.activeLine = last;
    this.centerActive(Boolean(forceScroll || seek));
  }
};

Karaoke.Renderer.prototype.centerActive = function (force) {
  const target = this.lines[this.activeLine];
  if (!target || !this.node.isConnected || (!force && performance.now() < this.manualUntil)) return;
  const reduced = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
  this.programmaticUntil = performance.now() + (reduced ? 100 : 1200);
  const outer = this.node.getBoundingClientRect();
  const inner = target.row.getBoundingClientRect();
  this.node.scrollTo({ top: Math.max(0, this.node.scrollTop + inner.top - outer.top - (this.node.clientHeight - inner.height) / 2), behavior: reduced || force ? "auto" : "smooth" });
};

Karaoke.Renderer.prototype.measure = function () {
  if (!this.node.isConnected || !this.lines.length) return;
  const scroller = this.scroller;
  const height = this.node.clientHeight;
  [[this.lines[0].row, "--karaoke-leading-space", "marginTop"], [this.lines[this.lines.length - 1].row, "--karaoke-trailing-space", "marginBottom"]].forEach(function (item) {
    const value = Math.max(0, (height - item[0].getBoundingClientRect().height) / 2 - (parseFloat(getComputedStyle(item[0])[item[2]]) || 0)).toFixed(2) + "px";
    if (scroller.style.getPropertyValue(item[1]) !== value) scroller.style.setProperty(item[1], value);
  });
};

Karaoke.Renderer.prototype.claim = function (container, presentation) {
  if (!this.model || !container || !container.isConnected) { this.release(); return; }
  const nativeList = Array.from(container.querySelectorAll("ul.lyricsScroller")).find(function (node) { return !node.closest(".amazify-karaoke-host"); });
  // The known wrapper can be empty when only a service has lyrics.
  if (!nativeList && !container.matches(".lyricsWrapper")) { this.release(); return; }
  const changed = container !== this.container || nativeList !== this.nativeList;
  const presentationChanged = this.node.dataset.presentation !== presentation;
  if (changed) {
    this.release();
    this.container = container;
    this.nativeList = nativeList;
    this.originalScroll = container.scrollTop;
    if (getComputedStyle(container).position === "static") {
      this.originalPosition = [container.style.getPropertyValue("position"), container.style.getPropertyPriority("position")];
      container.style.setProperty("position", "relative");
    }
    if (!this.scopeTemplate) this.scopeTemplate = Karaoke.lyricScopeTemplate(container);
    const nativeRow = nativeList && nativeList.querySelector(".lyricsLine") || this.scopeTemplate;
    const nativeText = nativeList && nativeList.querySelector(".lyricsText") || this.scopeTemplate;
    const renderer = this;
    function scope(template, node) {
      Array.from(node.attributes).forEach(function (attr) { if (/^data-v-/.test(attr.name)) node.removeAttribute(attr.name); });
      if (template) Array.from(template.attributes).forEach(function (attr) { if (/^data-v-[a-z0-9]+$/.test(attr.name)) node.setAttribute(attr.name, ""); });
    }
    scope(nativeList || this.scopeTemplate, this.scroller);
    this.lines.forEach(function (line) { scope(nativeRow, line.row); scope(nativeText, line.text); });
    container.appendChild(this.node);
    container.classList.add("amazify-karaoke-enhanced");
    this.nativeSurfaces = Array.from(container.children).filter(function (node) { return node !== renderer.node && (!nativeList || node === nativeList || node.contains(nativeList) || node.matches(".credits")); });
    this.nativeSurfaces.forEach(function (node) { node.setAttribute("data-amazify-karaoke-native", ""); });
    container.scrollTop = 0;
    renderer.measure();
    renderer.update(Karaoke.readPlaybackTime(), true);
  }
  this.node.dataset.presentation = presentation || "normal";
  const inactive = (nativeList || this.scroller).querySelector(".lyricsLine:not(.current) .lyricsText");
  if (inactive) {
    const textColor = getComputedStyle(inactive).color;
    const rowColor = getComputedStyle(inactive.parentNode).color;
    const color = textColor.indexOf("rgba(") === 0 ? textColor : rowColor;
    if (this.scroller.style.getPropertyValue("--karaoke-unsung-color") !== color) this.scroller.style.setProperty("--karaoke-unsung-color", color);
  }
  if (changed || presentationChanged) { this.measure(); this.centerActive(true); }
};

Karaoke.Renderer.prototype.release = function () {
  this.node.remove();
  this.nativeSurfaces.forEach(function (node) { node.removeAttribute("data-amazify-karaoke-native"); });
  this.nativeSurfaces = [];
  if (this.container) {
    this.container.classList.remove("amazify-karaoke-enhanced");
    if (this.originalPosition) {
      if (this.originalPosition[0]) this.container.style.setProperty("position", this.originalPosition[0], this.originalPosition[1]);
      else this.container.style.removeProperty("position");
    }
    this.container.scrollTop = this.originalScroll;
  }
  this.originalPosition = null;
  this.nativeList = null;
  this.container = null;
};

Karaoke.Renderer.prototype.destroy = function () {
  clearTimeout(this.scrollTimer);
  clearTimeout(this.resumeTimer);
  if (this.resizeObserver) this.resizeObserver.disconnect();
  this.release();
  this.model = null;
  this.lines = [];
};

// source: src/session.js
Karaoke.providerText = function (value) {
  return String(value || "").replace(/\s+/g, " ").trim();
};

Karaoke.stripProviderDecorations = function (value) {
  let text = Karaoke.providerText(value);
  if (!text) return "";
  text = text.replace(/\s*[\[(][^\])]*(remaster(?:ed)?|version|edit|mono|stereo|deluxe|expanded|anniversary|bonus|explicit|clean)[^\])]*[\])]/gi, " ");
  text = text.replace(/\s+-\s*(\d{4}\s+)?(remaster(?:ed)?|version|edit|mono|stereo|live|acoustic|deluxe|expanded)\b.*$/i, "");
  text = text.replace(/\s*\/\s*(remaster(?:ed)?|version|edit|mono|stereo|live|acoustic)\b.*$/i, "");
  text = text.replace(/[\s\-:;,/]+$/g, "");
  return Karaoke.providerText(text);
};

Karaoke.buildProviderQueries = function (track) {
  const base = {
    key: track.key,
    title: Karaoke.providerText(track.title),
    artists: Array.isArray(track.artists) ? track.artists.slice() : [],
    album: Karaoke.providerText(track.album),
    durationMs: Math.max(0, Number(track.durationMs) || 0)
  };
  const queries = [];
  const seen = new Set();

  function pushQuery(query) {
    if (!query.title || !Array.isArray(query.artists) || !query.artists.length) return;
    const normalized = {
      key: query.key,
      title: Karaoke.providerText(query.title),
      artists: query.artists.map(function (item) { return Karaoke.providerText(item); }).filter(Boolean),
      album: Karaoke.providerText(query.album),
      durationMs: Math.max(0, Math.round(Number(query.durationMs) || 0))
    };
    if (!normalized.title || !normalized.artists.length) return;
    const signature = [normalized.title, normalized.artists.join("|"), normalized.album, normalized.durationMs].join("\u001f").toLowerCase();
    if (seen.has(signature)) return;
    seen.add(signature);
    queries.push(normalized);
  }

  pushQuery(base);

  const strippedTitle = Karaoke.stripProviderDecorations(base.title);
  const strippedAlbum = Karaoke.stripProviderDecorations(base.album);
  if (strippedTitle && (strippedTitle !== base.title || strippedAlbum !== base.album)) {
    pushQuery({ key: base.key, title: strippedTitle, artists: base.artists, album: strippedAlbum, durationMs: base.durationMs });
  }

  if (strippedTitle && base.album) {
    pushQuery({ key: base.key, title: strippedTitle, artists: base.artists, album: "", durationMs: base.durationMs });
  }

  return queries.length ? queries : [base];
};

Karaoke.Session = function (provider) {
  this.provider = provider;
  this.track = null;
  this.model = null;
  this.status = "idle";
  this.providerStatus = null;
  this.generation = 0;
  this.requestKey = "";
  this.loaded = false;
  this.listeners = new Set();
  this.claims = new Set();
  this.defaultHost = null;
  this.viewHost = null;
  this.activeClaim = null;
  this.claimOrder = 0;
  this.raf = 0;
  this.timeout = 0;
  this.renderer = new Karaoke.Renderer(Karaoke.seek);
  this.destroyed = false;
};

Karaoke.Session.prototype.snapshot = function () {
  return Object.freeze({
    track: this.track ? Object.freeze({ key: this.track.key, hasLyrics: this.track.hasLyrics }) : null,
    status: this.status,
    source: this.model ? this.model.source : "amazon",
    type: this.model ? this.model.type : "",
    enhanced: Boolean(this.model && this.renderer.node.isConnected),
    suspended: !this.presentationEnabled(),
    // v1 compatibility: this means lyrics exist, not that Karaoke owns their renderer.
    hasLyrics: Boolean(this.model || (this.track && this.track.hasLyrics)),
    providerStatus: this.providerStatus ? Object.freeze(Object.assign({}, this.providerStatus)) : null
  });
};
Karaoke.Session.prototype.publish = function () {
  const snapshot = this.snapshot();
  this.listeners.forEach(function (listener) {
    try { listener(snapshot); } catch (error) { console.warn("[Karaoke Lyrics] listener failed", error); }
  });
};
Karaoke.Session.prototype.subscribe = function (listener) {
  this.listeners.add(listener);
  listener(this.snapshot());
  const session = this;
  return function () { session.listeners.delete(listener); };
};
Karaoke.Session.prototype.cancel = function () {
  clearTimeout(this.timeout);
  if (this.requestKey) this.provider.cancel(this.requestKey).catch(function () {});
  this.requestKey = "";
};
Karaoke.Session.prototype.setTrack = function (track) {
  if (this.destroyed) return;
  if (track && this.track && this.track.key === track.key) {
    const changed = this.track.hasLyrics !== track.hasLyrics;
    this.track = track;
    if (changed) this.publish();
    return;
  }
  if (!track && !this.track) return;
  this.cancel();
  this.generation += 1;
  this.track = track;
  this.model = null;
  this.loaded = false;
  this.providerStatus = null;
  this.status = track ? "native" : "idle";
  this.stopRaf();
  this.renderer.setModel(null);
  this.publish();
};
Karaoke.Session.prototype.host = function () {
  let selected = null;
  this.claims.forEach(function (claim) {
    if (!claim.container.isConnected) return;
    if (!selected || claim.priority > selected.priority || (claim.priority === selected.priority && claim.order > selected.order)) selected = claim;
  });
  this.activeClaim = selected;
  return selected ? selected.container : this.defaultHost;
};
Karaoke.Session.prototype.visible = function () {
  // Presentations may hide the lyrics region while centering artwork. Visibility
  // of the open view, not that region, controls lazy lookup and avoids a deadlock.
  if (!this.presentationEnabled()) return false;
  const host = this.viewHost || this.host();
  if (!host || !host.isConnected || document.visibilityState === "hidden") return false;
  const style = getComputedStyle(host);
  return style.display !== "none" && style.visibility !== "hidden" && host.getClientRects().length > 0;
};
Karaoke.Session.prototype.presentationEnabled = function () {
  this.host();
  return !this.activeClaim || this.activeClaim.enabled;
};
Karaoke.Session.prototype.ensureLoad = function () {
  if (this.destroyed || !this.track || this.loaded || this.requestKey || !this.visible()) return;
  const session = this;
  const generation = this.generation;
  const track = this.track;
  const requestKey = "karaoke:" + generation + ":" + Math.random().toString(36).slice(2);
  const queries = Karaoke.buildProviderQueries(track);
  let attempts = 0;
  this.requestKey = requestKey;
  this.status = "loading";
  this.publish();
  function current() { return !session.destroyed && generation === session.generation && requestKey === session.requestKey; }
  function finish(result) {
    if (!current()) return;
    clearTimeout(session.timeout);
    session.loaded = true;
    session.requestKey = "";
    session.model = result && result.trackKey === track.key && result.status === "ready" ? Karaoke.normalizeRich(result.payload, track.key) : null;
    session.providerStatus = {
      status: result && result.status || "unavailable",
      detail: result && result.detail || "",
      attempts: attempts
    };
    session.status = session.model ? "ready" : "native";
    session.renderer.setModel(session.model);
    session.syncHost();
    session.publish();
  }
  this.timeout = setTimeout(function () {
    if (!current()) return;
    session.provider.cancel(requestKey).catch(function () {});
    finish({ status: "unavailable", detail: "Provider timed out" });
  }, 28000);
  // Send only matching metadata, never native lyrics, artwork or Amazon account state.
  function loadAttempt(index) {
    if (!current()) return;
    if (!session.visible()) {
      session.cancel();
      session.status = "native";
      session.publish();
      return;
    }
    attempts = index + 1;
    return session.provider.load(queries[index], requestKey).then(function (result) {
      if (!current()) return result;
      if (result && result.status === "ready") return result;
      if (result && result.status === "no-lyrics" && index + 1 < queries.length) return loadAttempt(index + 1);
      return result;
    });
  }
  Promise.resolve().then(function () {
    return loadAttempt(0);
  }).then(finish).catch(function () { finish({ status: "unavailable" }); });
};
Karaoke.Session.prototype.setDefaultHost = function (container, view) {
  this.defaultHost = container || null;
  this.viewHost = view || null;
  this.syncHost();
  this.ensureLoad();
};
Karaoke.Session.prototype.claimHost = function (container, options) {
  if (this.destroyed || !container || container.nodeType !== 1) throw new TypeError("Lyrics host must be a live DOM element");
  const claim = { container: container, presentation: String(options && options.presentation || "normal"), priority: Number(options && options.priority || 0), enabled: !(options && options.enabled === false), order: ++this.claimOrder };
  this.claims.add(claim);
  this.syncHost();
  this.ensureLoad();
  const session = this;
  return function () {
    if (session.claims.delete(claim) && !session.destroyed) {
      session.syncHost();
      session.ensureLoad();
    }
  };
};
Karaoke.Session.prototype.syncHost = function () {
  const wasEnhanced = this.renderer.node.isConnected;
  const host = this.host();
  if (!this.presentationEnabled() && this.requestKey) {
    this.cancel();
    this.status = this.model ? "ready" : (this.track ? "native" : "idle");
    this.publish();
  }
  if (this.model && this.visible()) this.renderer.claim(host, this.activeClaim ? this.activeClaim.presentation : "normal");
  else this.renderer.release();
  if (!this.visible() || !this.renderer.node.isConnected) this.stopRaf();
  else {
    this.renderer.update(Karaoke.readPlaybackTime(), false);
    this.startRaf();
  }
  if (wasEnhanced !== this.renderer.node.isConnected) this.publish();
};
Karaoke.Session.prototype.stopRaf = function () { cancelAnimationFrame(this.raf); this.raf = 0; };
Karaoke.Session.prototype.startRaf = function () {
  if (this.destroyed || this.raf || !this.model || !this.renderer.node.isConnected || !this.visible() || !Karaoke.isPlaying()) return;
  const session = this;
  function frame() {
    session.raf = 0;
    if (session.destroyed || !session.model || !session.visible()) return;
    session.renderer.update(Karaoke.readPlaybackTime(), false);
    if (Karaoke.isPlaying()) session.raf = requestAnimationFrame(frame);
  }
  this.raf = requestAnimationFrame(frame);
};
Karaoke.Session.prototype.destroy = function () {
  this.destroyed = true;
  this.generation += 1;
  this.cancel();
  this.stopRaf();
  this.listeners.clear();
  this.claims.clear();
  this.renderer.destroy();
};

// source: src/integration.js
Karaoke.Integration = function (session) {
  this.session = session; this.timer = 0; this.interval = 0; this.observer = null;
  this.region = null; this.markedView = null; this.addedHasLyrics = false; this.placeholders = [];
};
Karaoke.Integration.prototype.removeRegion = function () {
  this.placeholders.forEach(function (node) { node.removeAttribute("data-amazify-karaoke-placeholder"); });
  this.placeholders = [];
  if (this.region) this.region.remove();
  this.region = null;
};
Karaoke.Integration.prototype.restoreView = function () {
  if (this.markedView) {
    this.markedView.classList.remove("amazify-karaoke-provider-lyrics");
    if (this.addedHasLyrics && !(this.session.track && this.session.track.hasLyrics)) this.markedView.classList.remove("hasLyrics");
  }
  this.markedView = null;
  this.addedHasLyrics = false;
  this.removeRegion();
};
Karaoke.Integration.prototype.hostForView = function (view) {
  const integration = this;
  let wrapper = view && Array.from(view.querySelectorAll(".lyricsContainer .lyricsWrapper")).find(function (node) { return !integration.region || !integration.region.contains(node); });
  const enhance = this.session.model && this.session.presentationEnabled();
  if (!view || !enhance || (this.markedView && this.markedView !== view)) this.restoreView();
  if (!view || !enhance) return wrapper || null;
  if (!this.markedView) {
    this.markedView = view;
    this.addedHasLyrics = !view.classList.contains("hasLyrics");
  }
  view.classList.add("hasLyrics", "amazify-karaoke-provider-lyrics");
  if (wrapper) {
    this.removeRegion();
    return wrapper;
  }
  if (!this.region || !this.region.isConnected) {
    this.removeRegion();
    const template = Karaoke.lyricScopeTemplate(view);
    const outer = view.querySelector(".lyricsContainer");
    const sizeClass = Array.from(view.classList).find(function (name) { return /^x[0-9]+$/.test(name); }) || "x4";
    wrapper = Karaoke.presentationElement(template, "div", "lyricsWrapper " + sizeClass);
    if (outer) {
      this.region = wrapper;
      this.placeholders = Array.from(outer.children);
      this.placeholders.forEach(function (node) { node.setAttribute("data-amazify-karaoke-placeholder", ""); });
      outer.appendChild(wrapper);
    } else {
      this.region = Karaoke.presentationElement(template, "div", "lyricsContainer");
      this.region.appendChild(wrapper);
      view.appendChild(this.region);
    }
    this.region.classList.add("amazify-karaoke-region");
    this.region.dataset.amazifyPluginId = "amazify.karaoke-lyrics";
  }
  return this.region.matches(".lyricsWrapper") ? this.region : this.region.querySelector(".lyricsWrapper");
};
Karaoke.Integration.prototype.start = function () {
  const integration = this;
  this.sync = function () {
    integration.timer = 0;
    const track = Karaoke.readTrack();
    integration.session.setTrack(track && track.title && track.artists.length ? track : null);
    const view = document.querySelector("#transportContainer.nowPlayingShowing .nowPlayingView");
    integration.session.setDefaultHost(integration.hostForView(view), view);
  };
  this.schedule = function (mutations) {
    if (mutations && mutations.every(function (item) { return item.target.closest && item.target.closest(".amazify-karaoke-host"); })) return;
    if (!integration.timer) integration.timer = setTimeout(integration.sync, 0);
  };
  this.observer = new MutationObserver(this.schedule);
  this.observer.observe(document.documentElement, { childList: true, subtree: true });
  this.interval = setInterval(this.sync, 250);
  document.addEventListener("visibilitychange", this.sync);
  this.sync();
};
Karaoke.Integration.prototype.destroy = function () {
  if (this.observer) this.observer.disconnect();
  clearTimeout(this.timer);
  clearInterval(this.interval);
  document.removeEventListener("visibilitychange", this.sync);
  this.restoreView();
};

// source: src/settings.js
Karaoke.addSettings = function (Amazify, session) {
  return Amazify.ui.addSettingsSection({
    id: "provider", title: "Lyrics providers",
    render: function (host) {
      const status = document.createElement("p");
      const clear = document.createElement("button");
      clear.type = "button";
      clear.textContent = "Clear lyrics cache";
      host.appendChild(status);
      host.appendChild(clear);
      let alive = true;
      const unsubscribe = session.subscribe(function (snapshot) {
        if (snapshot.status === "ready") {
          status.textContent = "Rich lyrics: " + snapshot.source;
          return;
        }
        if (snapshot.status === "loading") {
          status.textContent = "Checking Better Lyrics and Unison";
          return;
        }
        const provider = snapshot.providerStatus || {};
        let detail = "";
        if (provider.status === "no-lyrics") detail = provider.detail || "No compatible rich lyrics";
        else if (provider.status === "unavailable") detail = provider.detail || "Providers unavailable";
        const attempts = Number(provider.attempts || 0);
        status.textContent = "Native lyrics (no rich enhancement)" + (detail ? " - " + detail : "") + (attempts > 1 ? " (tried " + attempts + " metadata variants)" : "");
      });
      clear.addEventListener("click", function () {
        clear.disabled = true;
        Amazify.lyricsProvider.clearCache().then(function () {
          if (alive) status.textContent = "Lyrics cache cleared";
        }).catch(function () { if (alive) status.textContent = "Could not clear lyrics cache"; }).then(function () { if (alive) clear.disabled = false; });
      });
      return function () { alive = false; unsubscribe(); };
    }
  });
};

// source: src/bootstrap.js
Karaoke.bootstrap = function (Amazify) {
  if (!Amazify.lyricsProvider || Amazify.lyricsProvider.protocolVersion !== 2) throw new Error("Karaoke Lyrics 0.2.1 requires the Amazify 1.1.2 rich-lyrics companion");
  const session = new Karaoke.Session(Amazify.lyricsProvider);
  const integration = new Karaoke.Integration(session);
  const releaseCapability = Amazify.capabilities.provide("amazify.karaoke-lyrics.presentation", {
    version: "1.0.0",
    api: {
      getSnapshot: function () { return session.snapshot(); },
      subscribe: function (listener) { return session.subscribe(listener); },
      claimHost: function (container, options) { return session.claimHost(container, options); }
    }
  });
  const removeSettings = Karaoke.addSettings(Amazify, session);
  integration.start();
  return function () {
    try { removeSettings(); }
    finally { try { releaseCapability(); }
      finally { integration.destroy(); session.destroy(); }
    }
  };
};

return Karaoke.bootstrap(Amazify, manifest, source);
